"""mrfs

Revision ID: 13ba05b807e5
Revises: 859c1783886d
Create Date: 2023-12-18 17:47:56.553183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13ba05b807e5'
down_revision: Union[str, None] = '859c1783886d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=1500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['coments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('games', 'descripthion')
    op.add_column('games', sa.Column('description', sa.String(length=4500), nullable=True))
    op.alter_column('games', 'img',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=350),
               existing_nullable=False)

    op.add_column('news', sa.Column('description', sa.String(length=5500), nullable=True))
    op.alter_column('news', 'img',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=350),
               existing_nullable=False)
    op.drop_column('news', 'descripthion')
    op.add_column('users', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'description')
    op.add_column('news', sa.Column('descripthion', sa.VARCHAR(length=2000), autoincrement=False, nullable=False))
    op.alter_column('news', 'img',
               existing_type=sa.String(length=350),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('news', 'description')
    op.add_column('games', sa.Column('descripthion', sa.VARCHAR(length=1500), autoincrement=False, nullable=False))
    op.alter_column('games', 'img',
               existing_type=sa.String(length=350),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('games', 'description')
    op.drop_table('coments')
    # ### end Alembic commands ###
