"""nmsd

Revision ID: 859c1783886d
Revises: a4955233a510
Create Date: 2023-12-15 10:48:55.132207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '859c1783886d'
down_revision: Union[str, None] = 'a4955233a510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('games_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['games_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('games', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('games', 'descripthion',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1500),
               existing_nullable=False)
    op.add_column('news', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('img', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'role')
    op.drop_column('users', 'img')
    op.drop_column('news', 'created_at')
    op.alter_column('games', 'descripthion',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('games', 'created_at')
    op.drop_table('ratings')
    # ### end Alembic commands ###
